name: symfony-dev

services:
  app:
    container_name: app_dev_sy
    build:
      target: app_dev
    volumes:
      - '../project:/app'
      - './services/app/shared/dev/conf.d/app.ini:/usr/local/etc/php/conf.d/app.ini'
      - './services/app/shared/dev/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
    extra_hosts: # required for linux machines to run Xdebug
      - host.docker.internal:host-gateway
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=secret
      #https://www.jetbrains.com/help/phpstorm/debugging-a-php-cli-script.html
      - PHP_IDE_CONFIG=serverName=<name of the server configured on the PHP | Servers page of the Settings dialog>
    networks:
      - app-local-network

  app_nginx:
    image: nginx:latest
    depends_on:
      - app
    container_name: app_dev_nginx_sy
    ports:
      - "${SYMFONY_NGINX_HOST_PORT_HTTP:-80}:80"
      - "${SYMFONY_NGINX_HOST_PORT_HTTPS:-443}:443"
    volumes:
      - '../project:/app' ## Ensure nginx has access to the main directory
      - './services/nginx/shared/dev/conf.d:/etc/nginx/conf.d'
    networks:
      - app-local-network

networks:
  app-local-network:
    driver: bridge