services:
  app:
    container_name: app_dev
    build:
      target: app_dev
    volumes:
      - '../project:/app'
      - './services/app/shared/dev/conf.d:/usr/local/etc/php/conf.d'
    extra_hosts: # required for linux machines to run Xdebug
      - host.docker.internal:host-gateway
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=secret
    networks:
      - app-local-network

  app_nginx :
    container_name: app_dev_nginx
    ports:
      - "80:80"
    volumes:
      - './services/caddy/shared/dev/conf.d:/etc/caddy/conf.d'
    networks:
      - app-local-network

networks:
  app-local-network: