services:
  app:
    container_name: app_dev
    build:
      target: app_dev
    volumes:
      - '../project:/app'
      - './services/app/shared/dev/conf.d/app.ini:/usr/local/etc/php/conf.d/app.ini'
      - './services/app/shared/dev/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
    extra_hosts: # required for linux machines to run Xdebug
      - host.docker.internal:host-gateway
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=secret
    networks:
      - app-local-network

  app_caddy:
    container_name: app_dev_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '../project/public:/app/public'
      - './services/caddy/shared/dev/caddy/Caddyfile:/etc/caddy/Caddyfile'
    networks:
      - app-local-network

networks:
  app-local-network: